### PR TITLE
updated query in get_vivo_sponsorid to work with new ontology

### PR DESCRIPTION
**Pull request by atloiaco**
Updated the sparql query in get_vivo_sponsorid, query now matches what is found in the sv.cfg in the uf_examples/sponsors dir. Old query was returning no data.

### CODE REVIEW

**Comment by mconlon17** [comment]
The query in the example was returning no data at UF due to the prefix being used (uf v. ufVivo).  Adding FundingOrganization selector to the query is okay, but potentially removes some sponsors from the result set.  Any organization with a sponsorID is good to go as a sponsor.  Almost all will be in the FundingOrganization class, but this is not required for them to be a sponsor. I do understand that it is best that the filter and the get_vivo_sponsorid should match, otherwise data curators will be scratching their heads at some point.

**Comment by atloiaco** [comment]
Should I adjust the query to look for any sponsors with a sponsorID instead of looking to see if it is a considered a funding organization? The old query would return no data from vivo and this query is what is in sponsor_def.json, I could presumably change it in both places. The new query returns 6076 recrods from vivo and the input file has 7340 rows. I didn’t think it would be possible for a sponsor to not be considered a funding organization but knowing the rest of the data we get from uf / put in vivo anything is possible.

**Comment by mconlon17** [comment]
I would just pull on sponsorID and ignore FundingOrganization.

As you say, everything with a sponsorID _should_ be a FundingOrganization, but there is no guarantee of this.  And it does nothing for the query other than slow it down and potentially eliminate some orgs that have sponsor ids.

**Comment by atloiaco** [comment]
Mike,

I looked at this discrepancy this morning with Nicholas and we found that there was 34 funding organizations that have sponsorID’s but are not listed as fundingOrganizations. Nicholas created a construct query that added fundingOrganization to the 34 sponsors that did not have it as a type. Hopefully this should fix the issue going forward of entities with sponsorID’s also being funding orgs.

Alex

**Comment by atloiaco** [comment]
Mike,

Nicholas, Chris and I were looking over the sponsors data this morning as the pump process seemed to have run to completion. Looking at the initial output data of 10k things to add with 26k things to removed caused us to dig a little deeper. I have attached a text file with our findings.

Quick overall analysis is that the Labels in vivo are better than the ones coming from the pump we may want to favor labels already in vivo. As for the Sub it appears that there is some template that says that a sponsor should only contain certain assertions and everything else should be removed. After discussion we decided that we are only going to add new sponsors for the time being and will reevaluate fixing current sponsors going forward.

Alex


grep "label" sponsors_sub.rdf | wc -l
	Returns 3837 label changes. Most appear to be in vivo with a better label.
	For example http://vivo.ufl.edu/display/n68995
	In vivo the label is American Council of Learned Societie
	The sponsors_add.rdf label is Amer Cncl of Learned Societie

grep "type" sponsors_add.rdf | grep "core#FundingOrganization" | wc -l
	Returns 1264 sponors to add into vivo

grep "sponsorID" sponsors_add.rdf | wc -l
	Returns 1264 which validates the number of sponsors to add

----------------------------

grep "label" sponsors_sub.rdf | wc -l
	Returns 2573 most, if not all, of which look to be better than the labels in the add file

grep "core#" sponsors_sub.rdf | wc -l
	Returns 6147, containing ClinicalOrganization, Center, Foundation, Institute, etc
	It appears that it wants to remove any assertion that isnt a funding organization, agent, organization, or thing

grep "n945841495" sponsors_sub.rdf
	Using "n945841495" as an example wants to remove the following
	<http://vivo.ufl.edu/individual/n945841495> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/BFO_0000004> .
	<http://vivo.ufl.edu/individual/n945841495> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/BFO_0000002> .
	<http://vivo.ufl.edu/individual/n945841495> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/BFO_0000001> .
	<http://vivo.ufl.edu/individual/n945841495> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Company> .

	It would seem that these should stay in vivo though the pump has an idea of what a sponsor should look like.

grep "BFO_0000001" sponsors_sub.rdf | wc -l
	Returns 5958

grep "BFO_0000002" sponsors_sub.rdf | wc -l
	Returns 5958

grep "BFO_0000004" sponsors_sub.rdf | wc -l
	Returns 5958

rep "core#Company" sponsors_sub.rdf | wc -l
	Returns 3101

**Pull request merged**
