### PR TITLE
Fix corresponding author

### PR DESCRIPTION
**Pull request by indera**

### CODE REVIEW

**Comment by mconlon17** [comment]
I'm going to need some explanations.  Why utils.print?  What is this doing that can't be done with the logger?  What are the changes to sv.py?  add and sub were being made before.  Why change?

Inverse properties _should not_ be added by the pump or handled by the pump in way.  It is very important that inverse properties be handled by the inferencer to keep things clean.

**Comment by atloiaco** [comment]
Mike,

Starting with your first question. We added the utils.print as a quick way to print output to the terminal without having to go through the logger so we could quickly debug while we were building without having to worry about setting log levels.

The changes to sv.py were to accomidate the make_inverse_property function and to just print the query string, username and password for the api. The print statements could be removed without issue.

The big change was the adding of the make_inverse_subs, this was added because of what we saw when removing journals that had been added by the pump. We added the publishers and then journals in order. We then tried to sub the add file to back out the journals we had just added. After subbing the add file the links from the journal to the publisher were removed but the links from the publisher to the journal still existed and the link just went to a stub page. We let vivo sit for some time to see if the inferencer would remove the publisher to journal link but it did not. Thats when we created the make_inverse_subs function to make sure all the links are removed when running a sub.

**Comment by mconlon17** [comment]
I can't accept extraneous prints in the master branch.  All printing needs to be done by the logger so that it can be controlled by level by the user.  Can you remove these in a new pull request, or make them logger.debug calls to be used by everyone.

make_inverse_subs looks to be beyond the purpose of the pump.  The pump makes RDF from a spreadsheet, supporting add and update.  For update, it must remove RDF from VIVO and creates the sub RDF file to support the update.

When RDF is added to VIVO, the inferencer adds additional statements.  We know that this can lead to clutter -- future adds/subs may leave some inferenced assertions in place.  I'll look at the make_inverse_subs, it sounds specific -- in general, we do not have the information we need to remove parts of a graph -- some parts of the graph may need to remain (datetimes, for example), while other parts (roles and such) may be safely removed.  We can remove the add and add the sub, but we know that this does not restore VIVO due to the actions of the inferencer.

**Comment by indera** [comment]
We will be sending another pull request from the ctsit fork which is cleaner https://github.com/ctsit/vivo-pump/pull/1

**Pull request closed without merging**
