### PR TITLE
Revived old fix_bibtex.py

### PR DESCRIPTION
**Pull request by atloiaco**
I reimplemented the old fix_bibtex.py for the publisher names. I also changed all publisher names to uppercase to match the old process.

### CODE REVIEW

**Comment by mconlon17** [comment]
This could lead to problems.  Publishers are orgs and should be managed in a manner similar to orgs, otherwise you will generate conflicts between fix_bibtex and improve_org_names.  Perhaps all the translates from fix_bibtex can be added to the translate table in improve_org_names.  Otherwise you will have two, possibly conflicting, translate tables for organizations.

**Comment by atloiaco** [comment]
Do you think it would be better to just merge the dict from fix_bibtex into the improve_org_names dict?

**Comment by mconlon17** [comment]
Yes.  Much better.

**Comment by atloiaco** [comment]
I tried adding the dictionary from fix_bibtex into the improve_org_names function and it looks like it isnt picking up the dictionary entries from fix_bibtex. From the code it looks like the improve_org_names function does a search and replace on each word, as opposed to fix_bibtex.py which does a search and replace on each line. So Amer is getting replaced to American but AMERICAN SOCIETY MICROBIOLOGY isn't getting updated to AMERICAN SOCIETY FOR MICROBIOLOGY. Looks like it would require a rewrite of fix_bibtex or can keep them separate as separate functions.

**Comment by mconlon17** [comment]
Yes. `fix_bibtext` is line oriented.  `improve_org_name` is phrase oriented.  Both should be used.  `fix_bibtex` first with finishing by `improve_org_name` that way, all org names have gone through `improve_org_name` and you will have consistenly formatted names.  Otherwise you will be hoping that `fix_bibtex` handles all the things `improve_org_name` handles.

**Comment by atloiaco** [comment]
We can run fix_bibtex.py right after it is run through bib2csv. That would fix all the pubs before it goes through the improve org names.

**Pull request merged**
