### PR TITLE
Fix adding authors using static csv

### PR DESCRIPTION
**Pull request by indera**
Here is the code we worked with Alex on... It is not finished in the sense that the "corresponding" flag is not parsed properly since we are missing the proper syntax in `author_def.json`.

You don't have to accept this now, just be aware that we encountered some slowness in retrieving  author data (~200K entries) and we decided to use a static CSV file `author_list.csv` (in uf_examples/publications/filters/author_match_filter.py)

The plan is to have a cron job update the csv file (via a curl request) before we proceed with pubs ingest...

We would like to get more explanation on what "corresponding" means and why is that useful.

Thank you 

=== cron job query mentioned above
curl -d 'email=new_admin@vivo.ufl.edu' -d 'password=PASSWORD_SECRET_EDITED' -d 'query=PREFIX foaf:<http://xmlns.com/foaf/0.1/> PREFIX obo:<http://purl.obolibrary.org/obo/> PREFIX vcard:<http://www.w3.org/2006/vcard/ns#> SELECT ?person_uri ?fname ?lname ?mname WHERE { ?person_uri a foaf:Person . ?person_uri obo:ARG_2000028 ?contact_info . ?contact_info vcard:hasName ?name . ?name vcard:familyName ?lname . OPTIONAL { ?name vcard:givenName ?fname . }OPTIONAL { ?name vcard:middleName ?mname . }}' -H 'Accept: text/csv' 'https://dev.vivo.ufl.edu/vivo/api/sparqlQuery' > author_list.csv

### CODE REVIEW

**Comment by mconlon17** [comment]
Most academic papers have more than one author.  The median number of authors on a paper at UF is 7 (and increasing slowly over time).  One of these authors is chose by the authors as the corresponding author.  The corresponding author is the one that insures that the needs of the publisher are met (all forms signed by all authors), and responds to requests for information about the paper once it is published.  It is important for people reading the paper to know which of the authors is the corresponding author so that they can contact "the authors" (actually the corresponding author, if they have  a question about the paper.  The contact information of the corresponding author is often made available by the publisher, whereas contact information for the other authors is often withheld.  In VIVO, the corresponding author is designated by a property on an authorship.  The property can be used to identify corresponding authors, providing the expected information for readers of the paper.

**Comment by indera** [comment]
@mconlon17  thank you for merging and for the explanations about "corresponding".

As I understand it now the bibtex format does not have a dedicated field to indicate the "corresponding" author, so we only set it to "true" for publications with one author.

**Comment by misilot** [comment]
@indera I tried using the query above which does generate a  CSV file with 
person_uri, fname, lname, and mname (which get repeated after so many entries).

When I run prep_author I get the following error:

```
cat data_in/whatweknowarticle.bib \
	| python filters/bib2csv_filter.py \
	| python filters/author_prep_filter.py \
	| python filters/author_match_filter.py \
	> data_out/author_update_data.tsv
Entries: 1
Rows: 1
==> 17 columns in the input: [u'publisher', u'doi', u'author', u'ENTRYTYPE', u'journal', u'title', u'number', u'pages', u'volume', u'affiliation', u'note', u'link', u'year', u'ID', u'document_type', u'abstract', u'issn'] 
redacted
==> 9 columns in the output: ['corresponding', 'suffix', 'fit', 'uri', 'remove', 'middle', 'last', 'first', 'display_name']
5
Using static disambiguation file: author_list.csv
Traceback (most recent call last):
  File "filters/author_match_filter.py", line 50, in <module>
    file_name)
  File "/home/vivo/vivo-pump/disambiguate/utils.py", line 99, in get_vivo_disambiguation_data_from_csv
    case0_dict[k0] = append_to_dict_list(case0_dict, k0, uri)
  File "/home/vivo/vivo-pump/disambiguate/utils.py", line 33, in append_to_dict_list
    my_list = modified_dict[key]
KeyError: '"lastname"'
make: *** [prep_authors] Error 1

```

Any idea on what might be causing this? Thanks!

**Comment by indera** [comment]
It seems that the "key" passed to the "append_to_dict_list" function should not contain double quotes.
What version of python are you using?
I would add a debug line 

print("key is: {}".format(key))
before the 
my_list = modified_dict[key]

to confirm.

**Comment by misilot** [comment]
Python 2.7.5

I added the debug line, however it does not display when running make prep_authors

My csv file has no quotes in it except for accent marks in peoples names past where it is stopping.
```csv
person_uri,fname,lname,mname
https://vivo.school.edu/individual/n7478,Thomas,Misilo,
```

**Comment by indera** [comment]
I would try with python 3.4. 

Did you see in the log a line like:

> key is: "lastname" ?

**Comment by misilot** [comment]
@indera I will try and get python 3.4 installed on the system.

I found it in my data_out/author_update_data.tsv
However there were no quotes around lastname.

**Comment by misilot** [comment]
@indera I think to use Version 3.4, I would need to change vivopump and a bunch of other files. For example it looks like ConfigParser changed to configparser.

**Comment by misilot** [comment]
@indera I was able to get past error by removing the IndexError exception from utils.py.

Now onto why it can't match author's names.

**Pull request merged**
